Repository stolostron/klusterlet-addon-controller, pull requests merged in 2021-09, with the labels that each got.

#56 2.3.2 => 2.3.3
  COMPONENT_VERSION
  deploy/image-manifest-configmap.yaml
  pkg/apis/agent/v1/image_utils_test.go
  pkg/controller/klusterletaddon/klusterlet_addon_components_test.go
  pkg/controller/klusterletaddon/klusterlet_addon_crs_test.go
  version/version.go
Labels: dco-signoff: no

#59 add nodeselector to pods
  Makefile
  deploy/agent.open-cluster-management.io_klusterletaddonconfigs_crd.yaml
  deploy/crds-kube1.11/agent.open-cluster-management.io_applicationmanagers_crd.yaml
  deploy/crds-kube1.11/agent.open-cluster-management.io_certpolicycontrollers_crd.yaml
  deploy/crds-kube1.11/agent.open-cluster-management.io_iampolicycontrollers_crd.yaml
  deploy/crds-kube1.11/agent.open-cluster-management.io_policycontrollers_crd.yaml
  deploy/crds-kube1.11/agent.open-cluster-management.io_searchcollectors_crd.yaml
  deploy/crds-kube1.11/agent.open-cluster-management.io_workmanagers_crd.yaml
  deploy/crds-v1/agent.open-cluster-management.io_applicationmanagers_crd.yaml
  deploy/crds-v1/agent.open-cluster-management.io_certpolicycontrollers_crd.yaml
  deploy/crds-v1/agent.open-cluster-management.io_iampolicycontrollers_crd.yaml
  deploy/crds-v1/agent.open-cluster-management.io_policycontrollers_crd.yaml
  deploy/crds-v1/agent.open-cluster-management.io_searchcollectors_crd.yaml
  deploy/crds-v1/agent.open-cluster-management.io_workmanagers_crd.yaml
  deploy/crds/agent.open-cluster-management.io_applicationmanagers_crd.yaml
  deploy/crds/agent.open-cluster-management.io_certpolicycontrollers_crd.yaml
  deploy/crds/agent.open-cluster-management.io_iampolicycontrollers_crd.yaml
  deploy/crds/agent.open-cluster-management.io_policycontrollers_crd.yaml
  deploy/crds/agent.open-cluster-management.io_searchcollectors_crd.yaml
  deploy/crds/agent.open-cluster-management.io_workmanagers_crd.yaml
  pkg/apis/agent/v1/klusterletaddonconfig_types.go
  pkg/apis/agent/v1/types.go
  pkg/bindata/bindata_generated.go
  pkg/components/addon-operator/v1/klusterlet_addon_operator.go
  pkg/components/appmgr/v1/appmgr.go
  pkg/components/certpolicycontroller/v1/certpolicyctrl.go
  pkg/components/iampolicycontroller/v1/iampolicyctrl.go
  pkg/components/policyctrl/v1/policyctrl.go
  pkg/components/searchcollector/v1/search.go
  pkg/components/workmgr/v1/workmgr.go
  pkg/controller/klusterletaddon/klusterlet_addon_controller.go
Labels: lgtm, approved, dco-signoff: yes

#58 update api & add namespace in managedclusteraddon relatedobjects
  cmd/manager/main.go
  deploy/0000_01_addon.open-cluster-management.io_managedclusteraddons.crd.yaml
  go.mod
  go.sum
  pkg/controller/clustermanagementaddon/cluster_management_addon_controller.go
  pkg/controller/clustermanagementaddon/cluster_management_addon_controller_test.go
  pkg/controller/clustermanagementaddon/cluster_management_addon_setup.go
  pkg/controller/csr/csr_controller.go
  pkg/controller/csr/csr_controller_test.go
  pkg/controller/klusterletaddon/klusterlet_addon_components.go
  pkg/controller/klusterletaddon/klusterlet_addon_components_test.go
  pkg/controller/klusterletaddon/klusterlet_addon_controller.go
  pkg/controller/klusterletaddon/klusterlet_addon_controller_test.go
  pkg/controller/klusterletaddon/klusterlet_addon_crds.go
  pkg/controller/klusterletaddon/klusterlet_addon_crds_test.go
  pkg/controller/klusterletaddon/klusterlet_addon_crs.go
  pkg/controller/klusterletaddon/klusterlet_addon_crs_test.go
  pkg/controller/managedclusteraddon/managed_cluster_addon_controller.go
  pkg/controller/managedclusteraddon/managed_cluster_addon_controller_test.go
  pkg/controller/managedclusteraddon/managed_cluster_addon_predicate.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
Labels: lgtm, approved, dco-signoff: yes

#57 dd e2e test
  .github/workflows/go-presubmit.yml
  Makefile
  README.md
  build/e2e/install-e2e-cluster.sh
  build/e2e/kind-config.yaml
  go.mod
  go.sum
  pkg/controller/managedclusteraddon/managed_cluster_addon_controller.go
  pkg/controller/managedclusteraddon/managed_cluster_addon_registration.go
  test/e2e/e2e_suite_test.go
  test/e2e/loopback_test.go
Labels: lgtm, approved, dco-signoff: yes

#55 fixes: make deps failed
  Makefile
  build/install-dependencies.sh
Labels: lgtm, approved, dco-signoff: yes

#61 add e2e test for deleting addons
  README.md
  test/e2e/e2e_suite_test.go
  test/e2e/loopback_test.go
Labels: lgtm, approved, dco-signoff: yes

#60 add proxy env for each agent addons
  .github/workflows/go-presubmit.yml
  Makefile
  build/e2e/install-e2e-cluster.sh
  build/e2e/kind-config.yaml
  deploy/agent.open-cluster-management.io_klusterletaddonconfigs_crd.yaml
  deploy/crds-kube1.11/agent.open-cluster-management.io_applicationmanagers_crd.yaml
  deploy/crds-kube1.11/agent.open-cluster-management.io_certpolicycontrollers_crd.yaml
  deploy/crds-kube1.11/agent.open-cluster-management.io_iampolicycontrollers_crd.yaml
  deploy/crds-kube1.11/agent.open-cluster-management.io_policycontrollers_crd.yaml
  deploy/crds-kube1.11/agent.open-cluster-management.io_searchcollectors_crd.yaml
  deploy/crds-kube1.11/agent.open-cluster-management.io_workmanagers_crd.yaml
  deploy/crds-v1/agent.open-cluster-management.io_applicationmanagers_crd.yaml
  deploy/crds-v1/agent.open-cluster-management.io_certpolicycontrollers_crd.yaml
  deploy/crds-v1/agent.open-cluster-management.io_iampolicycontrollers_crd.yaml
  deploy/crds-v1/agent.open-cluster-management.io_policycontrollers_crd.yaml
  deploy/crds-v1/agent.open-cluster-management.io_searchcollectors_crd.yaml
  deploy/crds-v1/agent.open-cluster-management.io_workmanagers_crd.yaml
  deploy/crds/agent.open-cluster-management.io_applicationmanagers_crd.yaml
  deploy/crds/agent.open-cluster-management.io_certpolicycontrollers_crd.yaml
  deploy/crds/agent.open-cluster-management.io_iampolicycontrollers_crd.yaml
  deploy/crds/agent.open-cluster-management.io_policycontrollers_crd.yaml
  deploy/crds/agent.open-cluster-management.io_searchcollectors_crd.yaml
  deploy/crds/agent.open-cluster-management.io_v1_klusterletaddonconfig_cr.yaml
  deploy/crds/agent.open-cluster-management.io_workmanagers_crd.yaml
  deploy/role.yaml
  pkg/apis/agent/v1/image_utils.go
  pkg/apis/agent/v1/image_utils_test.go
  pkg/apis/agent/v1/klusterletaddonconfig_types.go
  pkg/apis/agent/v1/types.go
  pkg/apis/agent/v1/workmanager_types.go
  pkg/apis/agent/v1/zz_generated.deepcopy.go
  pkg/bindata/bindata_generated.go
  pkg/components/addon-operator/v1/klusterlet_addon_operator.go
  pkg/components/addons.go
  pkg/components/appmgr/v1/appmgr.go
  pkg/components/certpolicycontroller/v1/certpolicyctrl.go
  pkg/components/iampolicycontroller/v1/iampolicyctrl.go
  pkg/components/policyctrl/v1/policyctrl.go
  pkg/components/searchcollector/v1/search.go
  pkg/components/workmgr/v1/workmgr.go
  pkg/controller/add_cluster_management_addon.go
  pkg/controller/add_csr.go
  pkg/controller/add_klusterlet_addon.go
  pkg/controller/add_managed_cluster_addon.go
  pkg/controller/controller.go
  pkg/controller/klusterletaddon/globalproxy_controller.go
  pkg/controller/klusterletaddon/globalproxy_controller_test.go
  pkg/controller/klusterletaddon/klusterlet_addon_components.go
  pkg/controller/klusterletaddon/klusterlet_addon_components_test.go
  pkg/controller/klusterletaddon/klusterlet_addon_controller.go
  pkg/controller/klusterletaddon/klusterlet_addon_controller_test.go
  pkg/controller/klusterletaddon/klusterlet_addon_crds.go
  pkg/controller/klusterletaddon/klusterlet_addon_crds_test.go
  pkg/controller/klusterletaddon/klusterlet_addon_crs.go
  pkg/controller/klusterletaddon/klusterlet_addon_crs_test.go
  pkg/controller/managedclusteraddon/managed_cluster_addon_registration_test.go
  test/e2e/loopback_test.go
  test/e2e/resources/klusterletaddonconfig_cr.yaml
Labels: lgtm, approved, dco-signoff: yes

#62 fix null map in k8s 1.19
  deploy/crds-kube1.11/agent.open-cluster-management.io_workmanagers_crd.yaml
  deploy/crds-v1/agent.open-cluster-management.io_workmanagers_crd.yaml
  deploy/crds/agent.open-cluster-management.io_workmanagers_crd.yaml
  pkg/apis/agent/v1/workmanager_types.go
  pkg/bindata/bindata_generated.go
Labels: approved, dco-signoff: yes
