Repository stolostron/klusterlet-addon-controller, pull requests merged in 2021-12, with the labels that each got.

#80 2.4.1 => 2.4.2
  COMPONENT_VERSION
  deploy/image-manifest-configmap.yaml
  pkg/apis/agent/v1/image_utils_test.go
  pkg/controller/klusterletaddon/klusterlet_addon_components_test.go
  pkg/controller/klusterletaddon/klusterlet_addon_crs_test.go
  version/version.go
Labels: dco-signoff: no

#81 2.3.5 => 2.3.6
  COMPONENT_VERSION
  deploy/image-manifest-configmap.yaml
  pkg/apis/agent/v1/image_utils_test.go
  pkg/controller/klusterletaddon/klusterlet_addon_components_test.go
  pkg/controller/klusterletaddon/klusterlet_addon_crs_test.go
  version/version.go
Labels: lgtm, approved

#79 upgrade go to 1.17
  build/Dockerfile
  go.mod
Labels: lgtm, approved, dco-signoff: yes
