Repository stolostron/klusterlet-addon-controller, pull requests merged in 2022-05, with the labels that each got.

#125 2.4.4 => 2.4.5
  COMPONENT_VERSION
  deploy/image-manifest-configmap.yaml
  pkg/apis/agent/v1/image_utils_test.go
  pkg/controller/klusterletaddon/klusterlet_addon_components_test.go
  pkg/controller/klusterletaddon/klusterlet_addon_crs_test.go
  version/version.go
Labels: approved, dco-signoff: yes

#126 trigger build
  .triggerbuild
Labels: lgtm, approved, dco-signoff: yes

#127 trigger build release2.4
  .triggerbuild
  build/e2e/install-e2e-cluster.sh
  overlays/community/image-manifest-configmap.yaml
Labels: lgtm, approved, dco-signoff: yes

#130 trigger build
  .triggerbuild
Labels: lgtm, approved, dco-signoff: yes

#131 fix the imageoverride without imageregistry
  pkg/controller/addon/klusterlet_addon_controller.go
Labels: lgtm, approved, do-not-merge/hold, dco-signoff: yes
