Repository stolostron/klusterlet-addon-controller, pull requests merged in 2022-06, with the labels that each got.

#133 2.5.0 => 2.6.0
  COMPONENT_VERSION
  deploy/image-manifest-configmap.yaml
  pkg/apis/agent/v1/image_utils_test.go
  version/version.go
Labels: dco-signoff: no

#135 2.5.0 => 2.5.1
  COMPONENT_VERSION
  deploy/image-manifest-configmap.yaml
  pkg/apis/agent/v1/image_utils_test.go
  version/version.go
Labels: dco-signoff: yes

#136 Upgrade to go 1.18
  .github/workflows/go-presubmit.yml
  Makefile
  build/Dockerfile
  build/golangci.yml
  build/install-dependencies.sh
  build/run-lint-check.sh
  build/run-unit-tests.sh
  go.mod
  go.sum
Labels: lgtm, approved, dco-signoff: yes

#137 remove upgrade codes
  Makefile
  build/install-dependencies.sh
  deploy/crds-kube1.11/agent.open-cluster-management.io_applicationmanagers_crd.yaml
  deploy/crds-kube1.11/agent.open-cluster-management.io_certpolicycontrollers_crd.yaml
  deploy/crds-kube1.11/agent.open-cluster-management.io_iampolicycontrollers_crd.yaml
  deploy/crds-kube1.11/agent.open-cluster-management.io_policycontrollers_crd.yaml
  deploy/crds-kube1.11/agent.open-cluster-management.io_searchcollectors_crd.yaml
  deploy/crds-kube1.11/agent.open-cluster-management.io_workmanagers_crd.yaml
  deploy/crds-v1/agent.open-cluster-management.io_applicationmanagers_crd.yaml
  deploy/crds-v1/agent.open-cluster-management.io_certpolicycontrollers_crd.yaml
  deploy/crds-v1/agent.open-cluster-management.io_iampolicycontrollers_crd.yaml
  deploy/crds-v1/agent.open-cluster-management.io_policycontrollers_crd.yaml
  deploy/crds-v1/agent.open-cluster-management.io_searchcollectors_crd.yaml
  deploy/crds-v1/agent.open-cluster-management.io_workmanagers_crd.yaml
  deploy/crds/agent.open-cluster-management.io_applicationmanagers_crd.yaml
  deploy/crds/agent.open-cluster-management.io_certpolicycontrollers_crd.yaml
  deploy/crds/agent.open-cluster-management.io_iampolicycontrollers_crd.yaml
  deploy/crds/agent.open-cluster-management.io_policycontrollers_crd.yaml
  deploy/crds/agent.open-cluster-management.io_searchcollectors_crd.yaml
  deploy/crds/agent.open-cluster-management.io_workmanagers_crd.yaml
  go.mod
  go.sum
  pkg/apis/agent/v1/applicationmanager_types.go
  pkg/apis/agent/v1/certpolicycontroller_types.go
  pkg/apis/agent/v1/iampolicycontroller_types.go
  pkg/apis/agent/v1/image_utils.go
  pkg/apis/agent/v1/image_utils_test.go
  pkg/apis/agent/v1/policycontroller_types.go
  pkg/apis/agent/v1/searchcollector_types.go
  pkg/apis/agent/v1/types.go
  pkg/apis/agent/v1/workmanager_types.go
  pkg/apis/agent/v1/zz_generated.deepcopy.go
  pkg/bindata/bindata_generated.go
  pkg/bindata/bindatareader.go
  pkg/components/addon-operator/v1/klusterlet_addon_operator.go
  pkg/controller/addon/klusterlet_addon_controller.go
  pkg/controller/controller.go
  pkg/controller/globalproxy/globalproxy_controller.go
  pkg/controller/globalproxy/globalproxy_controller_test.go
  pkg/controller/managedcluster/managed_cluster_controller.go
  pkg/controller/managedcluster/managed_cluster_controller_test.go
  pkg/controller/upgrade/cleanup_controller.go
  pkg/controller/upgrade/cleanup_controller_test.go
  pkg/controller/upgrade/common.go
  pkg/controller/upgrade/upgrade_addon_controller.go
  pkg/controller/upgrade/upgrade_mgmtaddon_controller.go
  pkg/controller/upgrade/upgrade_mgmtaddon_controller_test.go
  pkg/dependencymagnet/doc.go
  pkg/helpers/imageregistry/client.go
  pkg/helpers/imageregistry/client_test.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
Labels: lgtm, approved, dco-signoff: yes

#139 2.4.5 => 2.4.6
  COMPONENT_VERSION
  deploy/image-manifest-configmap.yaml
  pkg/apis/agent/v1/image_utils_test.go
  pkg/controller/klusterletaddon/klusterlet_addon_components_test.go
  pkg/controller/klusterletaddon/klusterlet_addon_crs_test.go
  version/version.go
Labels: lgtm, approved, dco-signoff: yes

#140 2.3.11 => 2.3.12
  COMPONENT_VERSION
  deploy/image-manifest-configmap.yaml
  pkg/apis/agent/v1/image_utils_test.go
  pkg/controller/klusterletaddon/klusterlet_addon_components_test.go
  pkg/controller/klusterletaddon/klusterlet_addon_crs_test.go
  version/version.go
Labels: dco-signoff: yes

#138 Remove addon installnamespace auto correction
  pkg/controller/addon/klusterlet_addon_controller.go
  test/e2e/managedclusteraddon_test.go
Labels: lgtm, approved, dco-signoff: yes
