Repository stolostron/klusterlet-addon-controller, pull requests merged in 2023-01, with the labels that each got.

#173 Fix the image name for the governance-policy-framework addon
  pkg/apis/agent/v1/types.go
Labels: lgtm, approved, dco-signoff: yes

#174 2.5.6 => 2.5.7
  COMPONENT_VERSION
  deploy/image-manifest-configmap.yaml
  pkg/apis/agent/v1/image_utils_test.go
  version/version.go
Labels: lgtm, approved

#176 Moving the version from 2.7.0 to 2.8.0
  COMPONENT_VERSION
  pkg/apis/agent/v1/image_utils_test.go
  version/version.go
Labels: lgtm, dco-signoff: yes

#175 Update OWNERS file
  OWNERS
Labels: lgtm, approved, dco-signoff: yes

#177 2.7.0 => 2.8.0
  deploy/image-manifest-configmap.yaml
Labels: lgtm, approved, dco-signoff: yes
