Repository stolostron/klusterlet-addon-controller, pull requests merged in 2024-12, with the labels that each got.

#278 2.8.8 => 2.8.9
  COMPONENT_VERSION
Labels: dco-signoff: no

#279 :seedling: Update konflux CEL from release-2.13 to main
  .tekton/OWNERS
  .tekton/klusterlet-addon-controller-acm-211-pull-request.yaml
  .tekton/klusterlet-addon-controller-acm-211-push.yaml
  .tekton/klusterlet-addon-controller-acm-213-pull-request.yaml
  .tekton/klusterlet-addon-controller-acm-213-push.yaml
Labels: lgtm, approved, dco-signoff: yes

#281 :seedling: [release-2.12] update konflux files
  .tekton/OWNERS
  .tekton/klusterlet-addon-controller-acm-211-pull-request.yaml
  .tekton/klusterlet-addon-controller-acm-211-push.yaml
  .tekton/klusterlet-addon-controller-acm-212-pull-request.yaml
  .tekton/klusterlet-addon-controller-acm-212-push.yaml
Labels: lgtm, approved, dco-signoff: yes

#282 :seedling: [main] update konflux files
  .tekton/klusterlet-addon-controller-acm-213-pull-request.yaml
  .tekton/klusterlet-addon-controller-acm-213-push.yaml
Labels: lgtm, approved, dco-signoff: yes

#283 :seedling: [release-2.11] update konflux files
  .tekton/OWNERS
  .tekton/klusterlet-addon-controller-acm-211-pull-request.yaml
  .tekton/klusterlet-addon-controller-acm-211-push.yaml
Labels: do-not-merge/hold, dco-signoff: yes

#284 Update Konflux references
  .tekton/klusterlet-addon-controller-acm-210-pull-request.yaml
  .tekton/klusterlet-addon-controller-acm-210-push.yaml
Labels: approved, dco-signoff: yes

#290 :seedling: [release-2.10] update konflux files
  .tekton/OWNERS
  .tekton/klusterlet-addon-controller-acm-210-pull-request.yaml
  .tekton/klusterlet-addon-controller-acm-210-push.yaml
Labels: dco-signoff: yes

#285 fix gocovmerge cannot work using old go version
  build/run-unit-tests.sh
  build/test-package.sh
Labels: lgtm, approved, dco-signoff: yes
