Repository stolostron/klusterlet-addon-controller, pull requests merged in 2024-09, with the labels that each got.

#270 2.11.2=>2.11.3
  COMPONENT_VERSION
Labels: dco-signoff: yes

#271 2.10.5=>2.10.6
  COMPONENT_VERSION
Labels: dco-signoff: yes

#272 support get images without MCH
  cmd/manager/main.go
  pkg/apis/agent/v1/image_utils.go
  pkg/apis/agent/v1/image_utils_test.go
  pkg/apis/agent/v1/types.go
Labels: lgtm, approved, dco-signoff: yes

#273 2.10.6 => 2.10.7
  COMPONENT_VERSION
Labels: dco-signoff: no
