Repository stolostron/klusterlet-addon-controller, pull requests merged in 2025-01, with the labels that each got.

#304 [release 2.11] upgrade golang.org/x/net to 0.33.0
  go.mod
  go.sum
Labels: lgtm, approved, dco-signoff: yes

#303 [release 2.12] upgrade golang.org/x/net to 0.33.0
  go.mod
  go.sum
Labels: lgtm, approved, dco-signoff: yes

#302 upgrade golang.org/x/net to 0.33.0
  go.mod
  go.sum
Labels: lgtm, approved, dco-signoff: yes

#305 [release 2.10] upgrade golang.org/x/net to 0.33.0
  go.mod
  go.sum
Labels: lgtm, approved, dco-signoff: yes

#306 [release 2.9] upgrade golang.org/x/net to 0.33.0
  build/run-unit-tests.sh
  build/test-package.sh
  go.mod
  go.sum
Labels: lgtm, approved, dco-signoff: yes

#321 2.10.7 => 2.10.8
  COMPONENT_VERSION
Labels: dco-signoff: no

#322 2.11.5=>2.11.6
  COMPONENT_VERSION
Labels: dco-signoff: yes
